# Generated by Django 5.1.5 on 2025-01-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateTimeField(auto_now_add=True)),
                ('nombredelpadre', models.CharField(max_length=50)),
                ('nombredelamadre', models.IntegerField()),
                ('grado', models.CharField(max_length=50)),
                ('seccion', models.CharField(max_length=50)),
                ('fechaingreso', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
