# Generated by Django 5.1.5 on 2025-01-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='nombredelamadre',
            field=models.CharField(max_length=50),
        ),
    ]
